### PR TITLE
fix(k8s): pool size and autoscaling

### LINKED ISSUE #484: autoscaled size of kubernetes node pool gets shrunk
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
`Terraform v0.12.24`

### Affected Resource(s)
* scaleway_k8s_pool_beta

### Terraform Configuration Files

```hcl
resource "scaleway_k8s_pool_beta" "pool0" {
  cluster_id          = scaleway_k8s_cluster_beta.clustername.id
  name                = "pool0"
  node_type           = "DEV1-M"
  size                = 3
  autoscaling         = true
  autohealing         = true
  wait_for_pool_ready = true
  min_size            = 3
  max_size            = 6
}
```

### Expected Behavior

I expect actual sizes of the pool between 3 and 6 to take precendence the `size` of 3.

### Actual Behavior

Given the cluster has a size bigger then 3, it gets shrunk to the size of 3 during plan&apply.

### PR DESCRIPTION
**Pull request by Sh4d1**
Signed-off-by: Patrik Cyvoct <pcyvoct@scaleway.com>

Fixes #484

### CODE REVIEW

File: scaleway/resource_k8s_pool_beta.go [hunk 1]
```diff
@@ -115,6 +115,11 @@ func resourceScalewayK8SPoolBeta() *schema.Resource {
 				Computed:    true,
 				Description: "The Kubernetes version of the pool",
 			},
+			"actual_size": {
```
Comment (jerome-quere) [inline scaleway/resource_k8s_pool_beta.go:118]: Is `current_size` a better name ?

@remyleone

Comment (remyleone) [reply scaleway/resource_k8s_pool_beta.go:118]: yup current_size sounds better and is more descriptive

File: website/docs/r/k8s_pool_beta.html.markdown [hunk 2]
```diff
@@ -83,6 +84,7 @@ In addition to all above arguments, the following attributes are exported:
 - `created_at` - The creation date of the pool.
 - `updated_at` - The last update date of the pool.
 - `version` - The version of the pool.
+- `current_size` - The actual size of the pool.
```
Comment (jerome-quere) [inline website/docs/r/k8s_pool_beta.html.markdown:87]:
```suggestion
- `current_size` - The size of the pool at the time the state was updated.
```
