### PR TITLE
fix(k8s): only recreate default pool on its update

### LINKED ISSUE #374: Unable to delete Kapsule default pool
### Terraform Version
```
Terraform v0.12.18
+ provider.scaleway v1.13.0
```

### Affected Resource(s)
- scaleway_k8s_cluster_beta

### Terraform Configuration Files
```hcl
resource "scaleway_k8s_cluster_beta" "cluster" {
    cni           = "cilium"
    name          = "cluster"
    region        = "fr-par"
    tags          = [ "kube"]
    version       = "1.17.0"
}
```

### Debug Output
```
Error: "default_pool": required field is not set

  on scaleway.tf line 3, in resource "scaleway_k8s_cluster_beta" "cluster":
   3: resource "scaleway_k8s_cluster_beta" "cluster" {
```

### Expected Behavior
We should be able to delete the default pool, if we're using another one

### Actual Behavior
We can't delete the default pool, even though we can from the API/web interface

### Steps to Reproduce
1. `terraform apply`

### PR DESCRIPTION
**Pull request by Sh4d1**
Fixes #374 

Signed-off-by: Patrik Cyvoct <pcyvoct@scaleway.com>

### CODE REVIEW

File: scaleway/resource_k8s_cluster_beta.go [hunk 1]
```diff
@@ -480,38 +477,49 @@ func resourceScalewayK8SClusterBetaDefaultPoolUpdate(d *schema.ResourceData, m i
...
 			}
-		}
 
-		_, err := k8sAPI.UpdatePool(updateRequest)
-		if err != nil {
-			if !is404Error(err) {
-				return err
+			_, err := k8sAPI.UpdatePool(updateRequest)
+			if err != nil {
+				if !is404Error(err) {
```
Comment (kindermoumoute) [inline scaleway/resource_k8s_cluster_beta.go]: if this is a 404 something is wrong

Comment (kindermoumoute) [reply scaleway/resource_k8s_cluster_beta.go]: either force recreate, either error

Comment (Sh4d1) [reply scaleway/resource_k8s_cluster_beta.go]: Not it's desired behaviour. It was there before. If the default pool is deleted by hand, it should be recreated
